### ISSUE TITLE
Resonance Fitter gets stuck

### ISSUE THREAD

**Issue by pgysbers** [callum-mccracken/ncsmc_python#5]
After hitting "Done" the resonance fitter figure closes but the script hangs and the next one fails to appear.

**Comment by callum-mccracken** [comment]
should be fixed in the latest commit :)

**Comment by pgysbers** [comment]
Thanks Callum! Seem to work now. I also made sure to update matplotlib and tk (3.4.2 and 8.6.10)

**Comment by callum-mccracken** [comment]
Nice, thanks for the updates too!
